apiVersion: v1
kind: Service
metadata:
  name: example-service
spec:
  selector:
    app: example-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-service-deployment
spec:
  selector:
    matchLabels:
      app: example-service
  replicas: 1
  template:
    metadata:
      labels:
        app: example-service
    spec:
      containers:
        - name: example-service
          image: kicbase/echo-server:1.0
          ports:
            - containerPort: 8080
          env:
            - name: SOME_ENV_VAR
              value: "true"
          resources:
            requests:
              memory: "64Mi"
              cpu: "128m"
            limits:
              memory: "128Mi"
              cpu: "256m"
#          livenessProbe:
#            httpGet:
#              path: /ping
#              port: 80
#            initialDelaySeconds: 30
#            periodSeconds: 5
